### PR TITLE
Flexible Overlay for iOS and Android

### LINKED ISSUE #76: Fix the camera overlay
​
## Description
We've got a new overlay, but it doesn't look good... We need to make sure it's flexible and capable of being used in a production environment. At the moment it looks slap-dash and I wouldn't feel comfortable using it on a client project.

## Expected Behaviour
The overlay should look professional, sleek, and above all, it should work well. It should change depending on the options passed to it by the user.
​
## Current Behaviour
It looks slap-dash, it doesn't function correctly, there's no white-space. It's not fit to be released on client applications.
​
## Possible Solution
Fix the overlay so that it looks professional and we feel comfortable using it in client applications.
​
## Steps to Reproduce (for bugs)
1. Launch the Vuforia camera
1. Notice that it doesnt look right

## Context
At the moment, with the current overlay, there is no way we could use the plugin on client projects. It just wouldn't work.
​
## Your Environment

* Cordova version used: N/A
* Plugin version used: 3.0.0
* Plaforms affected: iOS & Android

### PR DESCRIPTION
**Pull request by dsgriffin**
## Description

Added a flexible overlay for iOS and Android, which takes into account imagery (close button, deviceIcon) as well as text length and device orientation.  

## Motivation and Context

Fixes #76 

## How Has This Been Tested?

Locally, using an iPhone 6S and an Android Galaxy S3.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by mattrayner** [comment]
Should the images not have a 1:1 ratio? Seems weird that they are all squashed?

**Comment by mattrayner** [comment]
This PR broke something - see #91

File: src/ios/ImageTargets/ImageTargetsViewController.mm [hunk 1]
```diff
@@ -677,10 +741,4 @@ -(void)test
 - (BOOL)prefersStatusBarHidden {
     return YES;
 }
-
--(bool) doUpdateTargets:(NSArray *)targets {
```
Comment (mattrayner) [inline src/ios/ImageTargets/ImageTargetsViewController.mm]: This block should not have been removed - for future reference
